# Generated by Django 4.1.2 on 2022-10-18 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=128, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('excerpt', models.CharField(max_length=255, verbose_name='Excerpt')),
                ('keywords', models.CharField(max_length=255, verbose_name='Keywords')),
                ('slug', models.SlugField(blank=True, max_length=128, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, upload_to='post_img/%Y/%m/%d', verbose_name='Image')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_content.category', verbose_name='Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comentaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('email', models.EmailField(max_length=64, verbose_name='E-mail')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_content.posts', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comentaries',
            },
        ),
    ]
